### ISSUE TITLE
Atom 1.17 "Project" title above tree view falls next to treeview if this package is enabled

### ISSUE THREAD

**Issue by rnyberg** [tiger4th/vertical-tabs#14] opened 2017-05-17 16:21 UTC

**Comment by Mootly** [comment] 2017-05-19 13:23
Confirmed.
This is consistent across UI themes and also happens with the vertical-tabs-right module.

This break occurred with the update to 1.17.0.

Don't have the old version to compare, but it looks like it is because the tab bar code has been duplicated in the new dock. Nothing differentiates the two except the 3rd-level parent container. Adding differentiating classes did not resolve it though.

Still poking.

**Comment by Mootly** [comment] 2017-05-19 13:41
Adding ".vertical" as prefix to LESS selectors (lines 4 & 10) and the atom-pane-container and .tab-bar selectors in vertical-tabs.js fixes the problem.

**Comment by tiger4th** [comment] 2017-05-21 09:25
I merged #15 and updated the package.
This issue was resolved at version 1.0.5.
Thanks @Mootly

**Closed** 2017-06-14 03:24 UTC
